# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Research', url: 'research.html'}
- {name: 'Posts', url: 'archive.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter',    link: 'https://twitter.com/fungalpals'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/fayth-tan-b791a9137/'}
- {icon: 'mastodon',  link: 'https://scicomm.xyz/@fungalpals'}
- {icon: 'envelope',   link: 'mailto:faythtan@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
